version: '3'
services:
    conda:
        build:
            dockerfile: ./Dockerfile
        env_file:
            - ./.env.wslg
        restart: always
        working_dir: '/docker/home/hasegawa/'
        tty: true
        image: conda
        container_name: 'conda'
        volumes:
            - /:/docker
            - /mnt/wslg:/mnt/wslg
            - /tmp/.X11-unix:/tmp/.X11-unix
