name: conda38
channnels:
    - conda-forge
    - anaconda
dependencies:
    - conda
    - python=3.8.5
    - numpy
    - matplotlib
    - netCDF4
    - cartopy
    - seaborn
    - scikit-learn
    - pandas
