services:
    py38:
        build:
            dockerfile: ./Dockerfile
        image: py38
        env_file:
            - ./.env_wslg
        restart: always
        tty: true
        container_name: 'py38'
        working_dir: '/docker/home/hasegawa/docker-python'
        volumes:
            - /:/docker
            - /mnt/wslg:/mnt/wslg
            - /tmp/.X11-unix:/tmp/.X11-unix

