version: '3'

services:
    gpu:
        build:
            dockerfile: ./Dockerfile
        deploy:
            resources:
                reservations:
                    devices:
                    - driver: nvidia
                      capabilities: [gpu]
        env_file:
            - ./.env_wslg
        restart: always
        working_dir: '/docker/home/hasegawa/docker-gpu/'
        tty: true
        image: 'gpu'
        container_name: 'gpu'
        volumes:
            - /:/docker
            - /mnt/wslg:/mnt/wslg
            - /tmp/.X11-unix:/tmp/.X11-unix

